example:
  property: I AM PRO
spring:
  cloud:
    consul:
      host: ${REGISTRY_HOST:localhost}
      port: ${REGISTRY_PORT:8500}
      discovery:
        healthCheckPath: http://${host}:${port}/actuator/health
        healthCheckInterval: 15s